#!/bin/bash
# Script pour tester le webhook localement avec Stripe CLI

echo "🚀 Instructions pour tester le webhook localement:"
echo ""
echo "1. Installer Stripe CLI:"
echo "   https://stripe.com/docs/stripe-cli"
echo ""
echo "2. Connecter votre compte Stripe:"
echo "   stripe login"
echo ""
echo "3. Écouter les webhooks (dans un terminal):"
echo "   stripe listen --forward-to localhost:3000/api/stripe/webhook"
echo ""
echo "4. Dans un autre terminal, déclencher un test:"
echo "   stripe trigger checkout.session.completed"
echo ""
echo "5. Ou créer une vraie session de test:"
echo "   stripe checkout sessions create \\"
echo "     --success-url=http://localhost:3000/success \\"
echo "     --cancel-url=http://localhost:3000/cancel \\"
echo "     --payment-method-types=card \\"
echo "     --mode=payment \\"
echo "     --line-items='[{\"price_data\":{\"currency\":\"eur\",\"product_data\":{\"name\":\"Test\"},\"unit_amount\":1000},\"quantity\":1}]'"
echo ""
echo "✅ Si le webhook fonctionne, vous verrez des logs dans votre console Next.js"